env: 
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

       
task:
    name: recovery
    timeout_in: 60m
    container:
      image: dazz111/ubuntu-sdk:build
      cpu: 7
      memory: 10G
    build_script:
      - bash build.sh
    
